---
- name: Fail if trying to install OpenJDK on SLES 11
  fail:
    msg: "OpenJDK is not available or supported on SLES 11."
  when: java == "openjdk" and ansible_os_family|lower == "suse" and ansible_distribution_major_version|int == 11

- name: Install OpenJDK
  package:
    name: "{{ openjdk_package }}"
    update_cache: yes
    state: present
  when: java == "openjdk"

- block:
    - name: Create the {{ oraclejdk_options.base_folder }} directory
      file:
        path: "{{ oraclejdk_options.base_folder }}"
        state: directory

    - name: Extract the Oracle JDK tarball
      unarchive:
        src: "{{ oraclejdk_options.tarball_location }}"
        dest: "{{ oraclejdk_options.base_folder }}"
        owner: root
        group: root
        mode: 0755
        remote_src: "{{ oraclejdk_options.remote_files }}"
        list_files: yes
        keep_newer: yes
      register: tarball_content

    - name: Set the new JDK folder name
      set_fact:
        jdk_folder: "{{ tarball_content.files[0] | regex_replace('/(.*)$','') }}"

    - name: Create the {{ oraclejdk_options.base_folder }}/latest symlink
      file:
        src: "{{ oraclejdk_options.base_folder }}/{{ jdk_folder }}"
        path: "{{ oraclejdk_options.base_folder }}/latest"
        state: link
        force: yes

    - name: Extract the JCE archive
      unarchive:
        src: "{{ oraclejdk_options.jce_location }}"
        dest: "{{ oraclejdk_options.base_folder }}/latest/jre/lib/security"
        owner: root
        group: root
        mode: 0755
        remote_src: "{{ oraclejdk_options.remote_files }}"

    - name: Copy the JCE jar files to {{ oraclejdk_options.base_folder }}/latest/jre/lib/security
      copy:
        src: "{{ oraclejdk_options.base_folder }}/latest/jre/lib/security/UnlimitedJCEPolicyJDK8/{{ item }}"
        dest: "{{ oraclejdk_options.base_folder }}/latest/jre/lib/security"
        force: yes
        remote_src: yes
      with_items:
        - local_policy.jar
        - US_export_policy.jar
  when: java == "oraclejdk"


# Solve KRB5 issues for JDK >= u242

- name: Capture installed Java version
  shell: /usr/bin/java -version 2>&1 | grep version | tr -d '"' | tr "_" " " | awk '{print $3"\n"$4}'
  register: version

- set_fact:
    installed_jdk_version: "{{ version.stdout_lines[0] }}"
    installed_jdk_update: "{{ version.stdout_lines[1] }}"

- name: Find java.security file
  find:
    paths: "{{ jdk_java_security_paths }}"
    pattern: "java.security"
    follow: yes
  register: java_security

- name: Apply workaround for Kerberos issues introduced in OpenJDK 1.8u242 and 11.0.6 (JDK-8215032)
  lineinfile:
    path: "{{ item.path }}"
    regexp: '^sun.security.krb5.disableReferrals='
    line: sun.security.krb5.disableReferrals=true
  with_items: "{{ java_security.files }}"
  when: >
    ((installed_jdk_version == '1.8.0' and installed_jdk_update|int >= 242)
      or (installed_jdk_version is version('11.0.6', '>=')))